### ISSUE TITLE
fetch_max_search_doc needs an independent example

### ISSUE THREAD

**Issue by patrickwalton** [OthersideAI/chronology#5]

**Comment by patrickwalton** [comment]
It doesn't run independently without await. Running by itself yields the error:

`RuntimeWarning: coroutine 'fetch_max_search_doc' was never awaited`

**Comment by bramses** [comment]
I can add this to the documentation as well. Are you calling the helper method directly or the `fetch_max_search_doc` wrapper?

**Comment by bramses** [comment]
Added a `must be awaited` header to all functions that need to be `awaited`: https://github.com/OthersideAI/chronology/blob/main/README.md#fetch_max_search_doc
